### ISSUE TITLE
Dash not loading

### ISSUE THREAD

**Issue by robrodriguezjr** [andreasdahl1987/DahlDesignDash#22]
I updated from version 1.10 to the latest 1.12 (Dash and properties) and since then the Dash does not load. I get the splash screen, but once on track it still shows the splash screen. Attached is the log file which shows some errors. thanks

[SimHub.log](https://github.com/andreasdahl1987/DahlDesignDash/files/10127395/SimHub.log)

**Comment by andreasdahl1987** [comment]
@robrodriguezjr Oh, surprising. I'll look into it. 
In the meantime, try adding this file (unzip and put in Program Files/SimHub/JavascriptExtensions folder). It will fix some of the errors, but not the main problem I think. 
[DahlDesign.zip](https://github.com/andreasdahl1987/DahlDesignDash/files/10127779/DahlDesign.zip)

**Comment by robrodriguezjr** [comment]
Thanks so much. I tried that file but no luck..RobertOn Nov 30, 2022, at 5:38 PM, Andreas Dahl ***@***.***> wrote:﻿
Oh, surprising. I'll look into it.
In the meantime, try adding this file (unzip and put in Program Files/SimHub/JavascriptExtensions folder). It will fix some of the errors, but not the main problem I think.
DahlDesign.zip

**Comment by andreasdahl1987** [comment]
I'm having a hard time replicating the issues you're having. I'm using Plugin 1.12.1, dash 1.12.2 and LED plugin 1.1.0. 

Could you try the following:
- Delete dashboard from DashTemplates folder
- Delete these files in the main folder: 
![image](https://user-images.githubusercontent.com/40788634/205178445-a04fa2a8-359f-40cd-aaf5-d70c8d73e9b6.png)

Get a fresh latest version of dashboard, properties plugin and LED plugin. 

If it doesnt work, can you send a screenshot of the issue?

**Comment by robrodriguezjr** [comment]
Hi Andreas,

Thanks for the help...

I deleted all the files you mentioned (I did not have dll.config file
however) then reinstalled everything with the latest. Still will not load.
Basically whether I open it on a VoCore screen or windowed, I do get the
default Dahl splash screen (black with white lines) but once I get in the
car and on track, it never changes to the actual dashboard. It was working
perfectly before. Also, I have two separate sim rigs in the house (separate
PCs), and it does not work on either one now...strange.

I'm not sure what type of screenshot you need...

Robert

**Comment by andreasdahl1987** [comment]
@robrodriguezjr That explains a lot, the Dahl splash screen not going away is because of the plugin crashing. The log file you sent is refering to a issue with conversion of a string to integer in [dashboard.cs](https://github.com/andreasdahl1987/DahlDesignProperties/blob/master/Sections/Dashboard.cs). It might be the issue referred to and supposedly fixed in this [commit](https://github.com/andreasdahl1987/DahlDesignProperties/pull/39/commits/9042959acca4c807ed6ed8ef890f75fd1f6f9c86). @photon1503, what do you think?

Same issue might be caused by these:
![image](https://user-images.githubusercontent.com/40788634/205405598-1bb830b6-853e-4594-97f6-9004124cd125.png)
Trying to convert "None" to an integer on first bootup.
Changed these and made a build file you can try.
![image](https://user-images.githubusercontent.com/40788634/205405670-5b2b7b41-eeea-4823-8912-e5596f00a731.png)

[DahlDesign.zip](https://github.com/andreasdahl1987/DahlDesignDash/files/10145002/DahlDesign.zip)

**Comment by robrodriguezjr** [comment]
Thanks

**Comment by robrodriguezjr** [comment]
Thanks. I tried with the new dll file you attached, but still does not
load. Below is a screenshot of the logs...

[image: image.png]

**Comment by andreasdahl1987** [comment]
Looks like no picture as uploaded, care to share the new log file? Will try making a version with the dashboard page settings removed in the evening. In the meantime you can use 1.10

**Comment by photon1503** [comment]
>  That explains a lot, the Dahl splash screen not going away is because of the plugin crashing. The log file you sent is refering to a issue with conversion of a string to integer 

yes, the initial setting needs to be some numeric value. Otherwise it will fail somewhere here

![image](https://user-images.githubusercontent.com/14548927/205436469-a1ed98ab-ab69-4381-8794-33b6081714ad.png)

**Comment by photon1503** [comment]
@andreasdahl1987 : also found this one
` public string DeltaScreenStartup { get; set; } = "LastLap";`

...
`   if (DashStartup)
            {
                DashStartup = !DashStartup;
                DeltaScreen.screenID = System.Convert.ToInt32(Base.Settings.DeltaScreenStartup);
            }`

**Comment by andreasdahl1987** [comment]
@photon1503 @robrodriguezjr Got spot, I made new .dll where this is also fixed. Try this one.
[DahlDesign.zip](https://github.com/andreasdahl1987/DahlDesignDash/files/10146281/DahlDesign.zip)

**Comment by robrodriguezjr** [comment]
Appreciate the effort, but sorry, still not working. Should I delete Simhub completely and start over? 

![image](https://user-images.githubusercontent.com/117524017/205445131-51a9b477-6064-4a9e-9802-a746f4490727.png)

**Comment by andreasdahl1987** [comment]
Try that. In the meantime more headscratching here 😅

**Comment by robrodriguezjr** [comment]
Finally, got it working!!
Before deleting Simhub entirely, I did a search for every file starting with "Dahl" in the Simhub folder, then deleted all of those. Then I reinstalled the latest DahlDash 1.12 and the properties file linked above. Now it loads! Thanks for your help! :)

FYI - Here is a list of the files found that I deleted.
![image](https://user-images.githubusercontent.com/117524017/205446455-b487dffa-fdf1-401f-a12d-19fdb67cc94a.png)

**Comment by andreasdahl1987** [comment]
Aah, glad to hear it:D at least we found some potential issues to fix.  Known issues with 1.12.2 is InCar Menu bug and IRating calculation bug, will be hotfixed in the evening.

**Comment by robrodriguezjr** [comment]
Ok, sounds good. BTW - if you need any help with testing, documentation, etc, let me know. I’m not a coder, but love tinkering with stuff sim racing related. I love your projects, (especially the dash) so happy to contribute. (Thinking of building a steering wheel soon.)RobertOn Dec 3, 2022, at 10:27 AM, Andreas Dahl ***@***.***> wrote:﻿
Aah, glad to hear it:D at least we found some potential issues to fix.  Known issues with 1.12.2 is InCar Menu bug and IRating calculation bug, will be hotfixed in the evening.

**Comment by andreasdahl1987** [comment]
Contribution is super welcome, that why I'm keeping everything open and on github. If you're not comfortable with the coding aspect, you can still help develop the dashboard by using the SimHub editor. @mcowger  found a way to work with the dashboard as a repository, follow the guide on the front page of this repository. If you've never used Git before, I suggest downloading GitHub Desktop, clode this repository to a folder on your computer and make the hard link as described. You can then keep up to date or test braches/pull requests through github desktop, as well as pushing your changes as pull request for everyone else to test. 

I'm working on an improved an updated documentation of the dashboard and plugin, splitting the old .pdf manual in 3 (property plugin, dashboard and LED plugin) and making gitbooks to make it all easiert to keep updated. I'm finished with the book for the plugin, now working on the dashboard. I think I'll work on that myself. Next up is DDC, which I think will be difficult for anyone else to write a guide to. 

At the moment working on the list of issues in the plugin repo and @photon1503 's pull request for major performance enhancing changes. 

Probably most needed is help mapping out cars and tracks. If you've got any you really want support for, you can help me filling in information in the [community spreadsheet.](https://docs.google.com/spreadsheets/d/1qfWFea4hHLUym3DeUvXeUEGuHvSiPWJE3HmdibiLCyk/edit#gid=0)

**Comment by robrodriguezjr** [comment]
Ok, great - will look into these and help where I can. I’m particularly interested in getting compatibility for the AMG EVO 2020, so will look into that as well. Quick question - in one of your DDU videos I noticed what looked like an iFlag display device. Does that work in conjunction with the SimhubDash, and did you build as well? I’m interested in building one myself. Thanks!Robert On Dec 3, 2022, at 2:59 PM, Andreas Dahl ***@***.***> wrote:﻿
Contribution is super welcome, that why I'm keeping everything open and on github. If you're not comfortable with the coding aspect, you can still help develop the dashboard by using the SimHub editor. @mcowger  found a way to work with the dashboard as a repository, follow the guide on the front page of this repository. If you've never used Git before, I suggest downloading GitHub Desktop, clode this repository to a folder on your computer and make the hard link as described. You can then keep up to date or test braches/pull requests through github desktop, as well as pushing your changes as pull request for everyone else to test.
I'm working on an improved an updated documentation of the dashboard and plugin, splitting the old .pdf manual in 3 (property plugin, dashboard and LED plugin) and making gitbooks to make it all easiert to keep updated. I'm finished with the book for the plugin, now working on the dashboard. I think I'll work on that myself. Next up is DDC, which I think will be difficult for anyone else to write a guide to.
At the moment working on the list of issues in the plugin repo and @photon1503 's pull request for major performance enhancing changes.
Probably most needed is help mapping out cars and tracks. If you've got any you really want support for, you can help me filling in information in the community spreadsheet.

**Comment by andreasdahl1987** [comment]
> 

The AMG EVO 2020 should not be too much work, since there is probably A LOT of similarities with the old AMG :)

**Comment by andreasdahl1987** [comment]
@robrodriguezjr The flag/screen thingie is a prototype for a screen I'll be releasing in the future some time. It works in conjunction with SimHub and will have its own dash template with many of the same features as the main Dashboard, but more of a Racelogic approach to it

**Comment by robrodriguezjr** [comment]
Thanks- sounds interesting, looking forward to it. RobertOn Dec 5, 2022, at 4:35 AM, Andreas Dahl ***@***.***> wrote:﻿
@robrodriguezjr The flag/screen thingie is a prototype for a screen I'll be releasing in the future some time. It works in conjunction with SimHub and will have its own dash template with many of the same features as the main Dashboard, but more of a Racelogic approach to it
